config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/herois/page/0")

  get "/herois/page/:page/" => "heroes#index", as: :heroes
  get "/herois/id/:id/" => "heroes#show", as: :hero
  get "/herois/id/:id/get_comics/:comics_page/" => "heroes#get_comics", as: :get_comics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def api_requester(url, params)
    params[:ts] = Time.now.to_s
    params[:apikey] = YAML.load_file("config/application.yml")["marvel_api_public_key"]
    params[:hash] = Digest::MD5.new.hexdigest(
          Time.now.to_s +
          YAML.load_file("config/application.yml")["marvel_api_private_key"] +
          YAML.load_file("config/application.yml")["marvel_api_public_key"]
    )

    return response = Typhoeus.get(
      url,
      params: params
    )
  end
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  def index
    page = params[:page].present? ? params[:page].to_i : 0

    @request = api_requester("https://gateway.marvel.com/v1/public/characters", { limit: 50, offset: page * 50 })

    @page_title = "Heŕois - MarvelTest"

    unless @request.code != 200
      @request = JSON.parse(@request.body)["data"]
      @pages = @request["total"].to_i / 50
    else
      redirect_to "/500"
    end
  end

  def show
    id = params[:id].present? ? params[:id].to_i : 0

    @request = api_requester("https://gateway.marvel.com/v1/public/characters/#{id}", {})

    unless @request.code != 200
      @request = JSON.parse(@request.body)["data"]
      @page_title = "#{@request["results"][0]["name"]} - MarvelTest"
      @page_image = @request["results"][0]["thumbnail"]["path"] + "/standard_fantastic." + @request["results"][0]["thumbnail"]["extension"]

      @comics = []
      @request["results"].each do |result|
        result["comics"]["items"][0..9].each do |comic|
          comic = api_requester(comic["resourceURI"], {})
          comic = JSON.parse(comic.body)["data"]["results"][0]
          @comics = @comics.push(comic)
        end
      end
    else
      redirect_to "/404"
    end
  end

  def get_comics
    id = params[:id].present? ? params[:id].to_i : 0
    comics_page = params[:comics_page].present? ? params[:comics_page].to_i : 0

    @request = api_requester("https://gateway.marvel.com/v1/public/characters/#{id}/comics", { limit: 10, offset: comics_page * 10 })
    unless @request.code != 200
      @comics = JSON.parse(@request.body)["data"]["results"]

      if @comics.size != 0
        render status: 200, json: @comics.to_json
      else
        render status: 204, json: { message: "204 No Content" }.to_json
      end
    else
      render status: 404, json: { message: "404 Page Not Found" }.to_json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/heroes/index.html.erb
<div class="container">
  <div class="superheros__index">
    <% @request["results"].each do |result| %>
      <%= link_to hero_path(result["id"]), class: "superheros__index--item" do %>
        <h4 class="superheros__index--name">
          <%= result["name"] %>
        </h4>
        <figure class="superheros__index--figure">
          <%= image_tag result["thumbnail"]["path"] + "/standard_fantastic." + result["thumbnail"]["extension"], class: "superheros__index--image" %>
        </figure>
      <% end %>
    <% end %>
    <div class="pagination">
      <% (0..@pages).each do |i| %>
        <%= link_to i, heroes_path(i), class: "pagination__page" %>
      <% end %>
    </div>
  </div>
</div>

app/views/heroes/show.html.erb
<div class="container">
  <% @request["results"].each do |result| %>
    <div class="superhero">
      <figure class="superhero__figure">
        <%= image_tag result["thumbnail"]["path"] + "/standard_fantastic." + result["thumbnail"]["extension"], class: "superhero__image" %>
      </figure>
      <span class="superhero__section--header">
        Informações
      </span>
      <div class="superhero__line">
        Nome: <span class="superhero__info"><%= result["name"] %></span>
      </div>
      <% if result["description"].present? %>
        <div class="superhero__line">
          Descrição: <span class="superhero__info"><%= result["description"] %></span>
        </div>
      <% end %>
      <div class="superhero__line">
        Modificado em: <span class="superhero__info"><%= Date.parse(result["modified"]).strftime("%d/%m/%Y")%></span>
      </div>

      <% if result["urls"].present? %>
        <span class="superhero__section--header">
          Links
        </span>
        <div class="superhero__line superhero__line--links">
          <% result["urls"].each do |url| %>
            <%= link_to url["url"], class: "superhero__info--link", target: "_blank" do %>
              <%= url["type"] %>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <span class="superhero__section--header">
        Quadrinhos
      </span>

      <div class="superhero__comics">
        <% @comics.each do |comic| %>
          <div class="superhero__comics--item">
            <span class="superhero__comics--name">
              <%= comic["title"] %>
            </span>
            <figure class="superhero__comics--figure">
              <%= image_tag comic["thumbnail"]["path"] + "/portrait_uncanny." + comic["thumbnail"]["extension"], class: "superhero__comics--image" %>
            </figure>
          </div>
        <% end %>
        <div class="superhero__comics--load">
          <span id="load_comics" data-hero="<%= result["id"] %>" data-page="0">Carregar mais +</span>
        </div>
      </div>

      <span class="superhero__section--header">
        Séries
      </span>

      <% unless result["series"]["available"] == 0 %>
          <% result["series"]["items"].each do |serie| %>
            <div class="superhero__line">
              <span class="superhero__info"><%= serie["name"] %></span>
            </div>
          <% end %>
      <% end %>

      <span class="superhero__section--header">
        Stories
      </span>

      <% unless result["stories"]["available"] == 0 %>
        <% result["stories"]["items"].each do |storie| %>
          <div class="superhero__line">
            <span class="superhero__info"><%= storie["name"] %></span>
          </div>
        <% end %>
      <% end %>

      <span class="superhero__section--header">
        Eventos
      </span>

      <% unless result["events"]["available"] == 0 %>
        <% result["events"]["items"].each do |event| %>
          <div class="superhero__line">
            <span class="superhero__info"><%= event["name"] %></span>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="pt-br">
  <head>
    <%= favicon_link_tag "icon.png" %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#EC1D24">
    <%= display_meta_tags og: {
      title: @page_title,
      description: @page_description,
      url: request.url,
      image: @page_image } %>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :modernizr %>
  </head>

  <body>
    <%= render "layouts/includes/alerts" %>
    <header>
      <div class="container">
        <h1 class="superheros__header">
          <%= link_to heroes_path(0), class: "back-btn" do %>
            <span class="back-btn--icon"></span>
          <% end %>
          <%= link_to "Marvel Heroes", heroes_path(0), class: "superheros__header--link" %>
        </h1>
      </div>
    </header>

    <div class="main">
      <%= yield %>
    </div>

    <footer>
    </footer>
  </body>
</html>

app/views/layouts/includes/_alerts.html.erb
<% flash.each do |key, value| %>
	<%
		if key != "success" && key != "danger" && key != "notice"
			key = "danger"
		end
	%>
    <div class="alert-message alert-message-<%= key %>">
      <%= value.html_safe %>
    </div>
<% end %>